### ISSUE TITLE
ostree-import request failed for release job with exception "name 'srcrepo' is not defined

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-releng-automation#103]
Error log from [testing release job](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline-release/466/console): 

```
[fedora-coreos-fedora-coreos-pipeline-release] Running shell script
+ set -xeuo pipefail
+ /var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py --build=31.20200420.2.0 --s3=fcos-builds/prod/streams/testing --repo=prod --fedmsg-conf=/etc/fedora-messaging-cfg/fedmsg.toml
Successfully started consumer thread
Sending ostree-import request for build 31.20200420.2.0
Waiting for a response to the sent request
Traceback (most recent call last):
  File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 108, in <module>
    sys.exit(main())
  File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 104, in main
    send_ostree_import_request(args)
  File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 83, in send_ostree_import_request
    validate_response(response)
  File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 98, in validate_response
    raise Exception(f"Importing failed: {response['failure-message']}")
Exception: Importing failed: name 'srcrepo' is not defined
```

**Comment by jlebon** [comment]
This was fixed in #104.
