### ISSUE TITLE
coreos-koji-tagger: failed to handle rust-zincati

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-releng-automation#7]
Pushing the latest rust-zincati to coreos-koji-data made coreos-koji-tagger fail with:

```
2019-07-11 18:09:07,121 DEBUG coreos_koji_tagger - Checking buildroottag f30-build
2019-07-11 18:09:07,121 DEBUG coreos_koji_tagger - Checking buildroottag f30-build
2019-07-11 18:09:07,122 DEBUG coreos_koji_tagger - Checking buildroottag module-afterburn-rolling-3020190622100113-a23e773d-build
2019-07-11 18:09:07,122 DEBUG coreos_koji_tagger - Checking buildroottag module-afterburn-rolling-3020190622100113-a23e773d-build
2019-07-11 18:09:07,122 DEBUG coreos_koji_tagger - Checking buildroottag f30-build
2019-07-11 18:09:07,122 DEBUG coreos_koji_tagger - Checking buildroottag f30-build
2019-07-11 18:09:07,122 DEBUG coreos_koji_tagger - Checking buildroottag f30-build
2019-07-11 18:09:07,123 DEBUG coreos_koji_tagger - Checking buildroottag module-zincati-rolling-3020190711144249-a23e773d-build
2019-07-11 18:09:07,123 ERROR fedora_messaging.twisted.protocol - Received unexpected exception from consumer Consumer(queue=e43390d1-acc7-4a46-983b-98d403c071f2, callback=<coreos_koji_tagger.Consumer object at 0x7f6a32d5c240>)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora_messaging/twisted/protocol.py", line 239, in _read
    yield threads.deferToThread(consumer.callback, message)
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib64/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 184, in __call__
    buildsinfo = get_buildsinfo_from_rpmnevras(desiredrpms)
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 409, in get_buildsinfo_from_rpmnevras
    releasever = get_releasever_from_buildroottag(buildroottag)
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 352, in get_releasever_from_buildroottag
    releasever = re.search('f(\d\d)', buildroottag).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-07-11 18:09:07,296 ERROR fedora_messaging.cli - Unexpected error occurred in consumer Consumer(queue=e43390d1-acc7-4a46-983b-98d403c071f2, callback=<coreos_koji_tagger.Consumer object at 0x7f6a32d5c240>): <twisted.python.failure.Failure builtins.AttributeError: 'NoneType' object has no attribute 'group'>
```

Looks like a regex mismatch?

Original PR at https://pagure.io/dusty/coreos-koji-data/pull-request/7.

**Comment by dustymabe** [comment]
https://github.com/coreos/fedora-coreos-releng-automation/pull/9
